addressbook/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

import contacts.views

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
  
     url(r'^$', contacts.views.ListContactView.as_view(),
         name='contacts-list',),

     url(r'^new$', contacts.views.CreateContactView.as_view(),
         name='contacts-new',),

     url(r'^edit/(?P<pk>\d+)/$', contacts.views.UpdateContactView.as_view(),
        name='contacts-edit',),

     url(r'^sms/(?P<pk>\d+)/$', contacts.views.SMSContactView.as_view(),
        name='contacts-sms',),

	 url(r'^calendarsms/', include('calendar_sms.urls')),

     url(r'^contacts/sms_send/$', contacts.views.sms_send, name='sms_send'),
    
     url(r'^delete/(?P<pk>\d+)/$', contacts.views.DeleteContactView.as_view(),
        name='contacts-delete',),
     
     url(r'^(?P<pk>\d+)/$', contacts.views.ContactView.as_view(),
        name='contacts-view',),
    
     url(r'^edit/(?P<pk>\d+)/addresses$', contacts.views.EditContactAddressView.as_view(),
        name='contacts-edit-addresses',),

     url(r'^accounts/', include('registration.backends.default.urls')),
    # Examples:
    # url(r'^$', 'addressbook.views.home', name='home'),
    # url(r'^addressbook/', include('addressbook.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)

urlpatterns += staticfiles_urlpatterns()

contacts/models.py
from django.db import models
from django.core.urlresolvers import reverse

class Contact(models.Model):

    first_name = models.CharField(
        max_length=255,
    )
    last_name = models.CharField(
        max_length=255,
    )    

    number = models.CharField(
        max_length=255,
    )

    email = models.EmailField()

    def __str__(self):

        return ' '.join([
            self.first_name,
            self.last_name,
        ])
    def get_absolute_url(self):
	
	return reverse('contacts-view', kwargs={'pk': self.id})

class Address(models.Model):

    contact = models.ForeignKey(Contact)
    address_type = models.CharField(
        max_length=10,
    )

    address = models.CharField(
        max_length=255,
    )
    city = models.CharField(
        max_length=255,
    )
    state = models.CharField(
        max_length=2,
    )
    postal_code = models.CharField(
        max_length=20,
    )

    class Meta:
        unique_together = ('contact', 'address_type',)

class Sloonodaten(models.Model):

	user = models.CharField(max_length=20)
        pw   = models.CharField(max_length=40)

# Create your models here.

contacts/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.forms.models import inlineformset_factory
from contacts.models import Contact, Address


class ContactForm(forms.ModelForm):

    confirm_email = forms.EmailField(
        "Confirm email",
        required=True,
    )

    class Meta:
        model = Contact

    def __init__(self, *args, **kwargs):

        if kwargs.get('instance'):
            email = kwargs['instance'].email
            kwargs.setdefault('initial', {})['confirm_email'] = email

        return super(ContactForm, self).__init__(*args, **kwargs)
   
    def clean(self):

        if (self.cleaned_data.get('email') !=
            self.cleaned_data.get('confirm_email')):

            raise ValidationError(
                "Email addresses must match."
            )

        return self.cleaned_data

ContactAddressFormSet = inlineformset_factory(
	Contact,
	Address,
)

contacts/views.py
from django.views.generic import ListView, UpdateView, DeleteView, DetailView
from contacts.models import Contact, Address, Sloonodaten
import urllib2
from django.core.urlresolvers import reverse
from django.views.generic import CreateView
import forms
from django.http import HttpResponseRedirect, HttpResponse

class ListContactView(ListView):

    model = Contact
    template_name = 'contact_list.html'
    
    def get_success_url(self):
	return reverse('contacts-list')

class CreateContactView(CreateView):

	model = Contact
	template_name = 'edit_contact.html'
        form_class = forms.ContactForm         
  
	def get_success_url(self):
		return reverse('contacts-list')

class CreateContactView(CreateView):

    model = Contact
    template_name = 'edit_contact.html'

    def get_success_url(self):
        return reverse('contacts-list')

    def get_context_data(self, **kwargs):

        context = super(CreateContactView, self).get_context_data(**kwargs)
        context['action'] = reverse('contacts-new')

        return context

class UpdateContactView(UpdateView):

    model = Contact
    template_name = 'edit_contact.html'
    form_class = forms.ContactForm

    def get_success_url(self):
        return reverse('contacts-list')

    def get_context_data(self, **kwargs):

        context = super(UpdateContactView, self).get_context_data(**kwargs)
        context['action'] = reverse('contacts-edit', kwargs={'pk': self.get_object().id})

        return context

class SMSContactView(UpdateView):

    model = Contact
    template_name = 'sms_contact.html'
    form_class = forms.ContactForm

def sms_send(request):
	text = request.POST['sms_text']
	nummer = request.POST['sms_nummer']
        nummer_send = str(nummer).replace("0", "49", 1)
        text_send = text.replace(" ", "+")
	user = Sloonodaten.objects.get(pk=1)
	urllib2.urlopen("http://www.sloono.de/API/httpsms.php?user=" + user.user + "&password=" + user.pw + "&typ=1&text=" + text_send + "&to=%2B" + nummer_send).read()
	return HttpResponseRedirect('/')
	

class DeleteContactView(DeleteView):

    model = Contact
    template_name = 'delete_contact.html'

    def get_success_url(self):
        return reverse('contacts-list')

class ContactView(DetailView):

	model = Contact
	template_name = 'contact.html'

class EditContactAddressView(UpdateView):

    model = Contact
    template_name = 'edit_addresses.html'
    form_class = forms.ContactAddressFormSet

    def get_success_url(self):

        # redirect to the Contact view.
        return self.get_object().get_absolute_url()

contacts/templates/base_contact.html
{% load staticfiles %}
<html>
  <head>
    <link href="{% static 'bootstrap-3.0.0-wip/dist/css/bootstrap.min.css' %}"
          rel="stylesheet" media="screen">
    <link href="{% static 'test.css' %}"
          rel="stylesheet" media="screen">
    <script src="{% static 'bootstrap-3.0.0-wip/dist/js/bootstrap.min.js' %}"></script>
  </head>

  <body>
<!-- Navigation Bar -->
<nav>
  <h1>Ghostbook</h1>
{% if user.is_authenticated %}
<p class="navbar-text pull-left">Hallo {{ user.username }}, <a href="/accounts/logout/">Abmelden</a></p>
{% endif %}
</nav>
<!-- Navigation Ends -->

<article>
    {% if user.is_authenticated %}
    <br>
    {% block content %}
    {% endblock %}
    {% else %}
	<h2>Herzlich Willkommen beim Ghostbook</h2>
	<h2> Melde dich bitte an oder bitte um Kontakt auf unserer: <a href="/calendarsms/">Kontaktseite</a> </h2>
	{% endif %}
</article>
 
<footer>
<br>
<br>
<p>--------------------</p>
<p><a href="/">Startseite</a> {% if user.is_authenticated %}<a href="/accounts/logout/">Abmelden</a>{% else %}<a href="/accounts/login/">Anmelden</a> <a href="/accounts/register/">Registrieren</a>{% endif %}</p>
<p>&copy; Codebusters</p>
</footer>
  
  </body>
</html>

contacts/templates/contact.html
{% extends "base_contact.html" %}

{% block content %}

<h2>{{ contact }}</h2>

<p>Email: {{ contact.email }}</p>

<ul>
{% for address in contact.address_set.all %}
   <li>{{ address.address }}<br/><br/>
       {{ address.city }} {{ address.state }}<br/><br/>
       {{ address.postal_code }}
   </li>
{% endfor %}
</ul>
<a href="{% url "contacts-list" %}">back to list</a>

{% endblock %}

contacts/templates/contact_list.html
{% extends "base_contact.html" %}

#{% block content %}



<h2>Contacts</h2>

<ul class = boo>
  {% for contact in object_list %}
    <li class="contact">{{ contact }}
	<a href="{% url "contacts-edit" pk=contact.id %}">
	<button type="submit" class="btn a btn-xs">edit</button></a>
	<a href="{% url "contacts-sms" pk=contact.id %}"> 
	<button type="submit" class="btn b btn-xs"> sms</button></a>
    </li>
  {% endfor %}
</ul>

<a href="{% url "contacts-new" %}"><button type="submit" class="btn add btn-sm"> add contact</button></a>
{% endblock %}

{% if contact.id %}
<h1>Edit Contact</h1>
{% else %}
<h1>Add Contact</h1>
{% endif %}

{% for contact in object_list %}
    <li class="contact">
      <a href="{{ contact.get_absolute_url }}">{{ contact }}</a>
      (<a href="{% url "contacts-edit" pk=contact.id %}">edit</a>)
    </li>
{% endfor %}

<form action="{{ action }}" method="POST">

contacts/templates/delete_contact.html
{% extends "base_contact.html" %}

{% block content %}

<h2>Delete Contact</h2>

<p>Are you sure you want to delete the contact {{ contact }}?</p>

<form action="{% url "contacts-delete" pk=contact.id %}" method="POST">
  {% csrf_token %}

  <input type="submit" value="Yes, delete." />
  <a href="{% url "contacts-list" %}">No, cancel.</a>
</form>

{% endblock %}

contacts/templates/edit_addresses.html
{% extends "base_contact.html" %}

{% block content %}

<h2>Edit Addresses</h2>

<p>Editing addresses for {{ contact }}</p>

<form action="{% url "contacts-edit-addresses" pk=contact.id %}"
      method="POST">
    {% csrf_token %}
    {{ form.management_form }}
    {% for address_form in form %}

        <ul>
        {{ address_form.as_ul }}
        </ul>

    {% endfor %}

    <input type="submit" value="Save" />
</form>

<a href="{% url "contacts-list" %}">back to list</a>

{% endblock %}

contacts/templates/edit_contact.html
{% extends "base_contact.html" %}

{% block content %}

{% if contact.id %}
<h2>Edit Contact</h2>
{% else %}
<h2>Add Contact</h2>
{% endif %}

<form action="{{ action }}" method="POST">
  {% csrf_token %}

  {% for field in form %}
  <div id="{{ field.auto_id }}_container">
    {{ field.help_text }}
    <div>
      {{ field.label_tag }} {{ field }}
    </div>
    <div id="{{ field.auto_id }}_errors">
      {{ field.errors }}
    </div>
  </div>
  {% endfor %}

  <input id="save_contact" type="submit" value="Save" />
</form>

{% if contact.id %}
<a href="{% url "contacts-edit-addresses" pk=contact.id %}">
  Edit Addresses
</a>
<a href="{% url "contacts-delete" pk=contact.id %}">Delete</a>
{% endif %}

<a href="{% url "contacts-list" %}">back to list</a>

{% endblock %}

contacts/templates/sms_contact.html
{% extends "base_contact.html" %}

{% block content %}
<h2>{{ contact }}</h2>

<div class="input-group">
<form class="col-lg-6" action="/contacts/sms_send/" method="post">
{% csrf_token %}
<label>SMS Senden</label>
<input name="sms_nummer" class="form-control" value="{{ contact.number }}">
<textarea maxlength="160" name="sms_text" class="form-control" placeholder="Hier kommt dein Text rein"></textarea>
<button class="btn add" id="send" type="submit">Senden</button>
</form>
</div>
{% endblock %}